### ISSUE TITLE
You used chatGPT for the description 💀

### ISSUE THREAD

**Issue by Perseus333** [GaslightGod/GaslightGod#1]
Seriously why?

Cool projects tho, love the chess repo. 👍

**Comment by GaslightGod** [comment]
Honestly just because I'm lazy.

**Comment by Perseus333** [comment]
> Honestly just because I'm lazy.

yeah, wiriting is hard.

**Comment by GaslightGod** [comment]
Efficiency is key right? I can't imagine being supercilious over a custom descriptor

**Comment by Perseus333** [comment]
> Efficiency is key right? I can't imagine being supercilious over a custom descriptor

I'm gonna make as if I understood what a custom descriptor is. No idea.
